name: wegame
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bitsdojo_window: ^0.1.6
  pocketbase: any
  cached_network_image: ^3.4.1
  get: ^4.6.6
  fluttertoast: ^8.2.7
  dio: ^5.4.1
  just_audio: ^0.9.36
  path_provider: ^2.1.5 # Or a more recent version
  fvm: ^3.2.1
  sqflite: ^2.4.1
  sqflite_common_ffi: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
